<?php

require "../auth.php";
require "../db.php";
require __DIR__ . "/../lib/fpdf.php";

date_default_timezone_set('America/Los_Angeles');

/*
|--------------------------------------------------------------------------
| Receive data from view.php
|--------------------------------------------------------------------------
*/

$report   = $_POST["report"] ?? $_GET["report"] ?? "traffic";
$reportId = $_POST["rid"] ?? $_GET["rid"] ?? null;
$chart    = $_POST["chart"] ?? null;

/*
|--------------------------------------------------------------------------
| Prepare chart image if provided
|--------------------------------------------------------------------------
*/

$tmpChart = null;

if ($chart) {

    $chart = str_replace('data:image/png;base64,','',$chart);
    $chart = base64_decode($chart);

    $tmpChart = "/tmp/chart_" . uniqid() . ".png";
    file_put_contents($tmpChart,$chart);

}

/*
|--------------------------------------------------------------------------
| PDF class
|--------------------------------------------------------------------------
*/

class ReportPDF extends FPDF {

function Footer() {

$this->SetY(-15);
$this->SetFont('Arial','I',9);

$this->Cell(
0,
10,
'Page '.$this->PageNo().' | Generated by CSE135 Reporting System',
0,
0,
'C'
);

}

}

/*
|--------------------------------------------------------------------------
| Begin PDF
|--------------------------------------------------------------------------
*/

$pdf = new ReportPDF();
$pdf->SetAutoPageBreak(true,20);
$pdf->AddPage();

/*
|--------------------------------------------------------------------------
| Header
|--------------------------------------------------------------------------
*/

$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'CSE 135 Analytics Dashboard Report',0,1);

$pdf->SetFont('Arial','',11);

$pdf->Cell(40,7,'Report Type:',0);
$pdf->Cell(0,7,ucfirst($report),0,1);

$pdf->Cell(40,7,'Generated:',0);
$pdf->Cell(0,7,date("M j, Y g:i A T"),0,1);

if ($reportId) {

$pdf->Cell(40,7,'Report ID:',0);
$pdf->Cell(0,7,$reportId,0,1);

}

$pdf->Ln(6);

/*
|--------------------------------------------------------------------------
| Insert Chart (from Chart.js)
|--------------------------------------------------------------------------
*/

if ($tmpChart && file_exists($tmpChart)) {

    $pdf->SetFont('Arial','B',12);
    $pdf->Cell(0,8, ucfirst($report) . ' Visualization',0,1);

    // 1. Get the original pixel dimensions of the stitched PNG
    $size = getimagesize($tmpChart);
    $origWidth = $size[0];
    $origHeight = $size[1];

    // 2. Conditionally scale and position based on report type
    if ($report === "performance") {
        // Scale down the tall, double-stacked performance charts
        $pdfWidth = 130; 
        
        // Center the smaller image. (210mm standard A4 width - 130mm image width) / 2 = 40mm
        $xPos = 40; 
    } else {
        // Default full width for normal single-chart reports
        $pdfWidth = 180;
        $xPos = 15;
    }

    // 3. Calculate the exact scaled height to maintain the aspect ratio
    $pdfHeight = ($origHeight / $origWidth) * $pdfWidth;

    // Push to new page if it's still going to clip the bottom margin
    if ($pdf->GetY() + $pdfHeight > 260) {
        $pdf->AddPage();
    }

    // 4. Insert the image using the dynamic X position and Width
    $pdf->Image($tmpChart, $xPos, $pdf->GetY(), $pdfWidth);

    // 5. Dynamically move the text cursor down past the image + 10 units of padding
    $pdf->Ln($pdfHeight + 10);

}

/*
|--------------------------------------------------------------------------
| Report Tables
|--------------------------------------------------------------------------
*/

if ($report === "traffic") {

$result = $mysqli->query("
SELECT url, COUNT(*) AS visits
FROM events
GROUP BY url
ORDER BY visits DESC
LIMIT 10
");

$pdf->SetFillColor(230,230,230);

$pdf->SetFont('Arial','B',12);
$pdf->Cell(120,8,'URL',1,0,'L',true);
$pdf->Cell(40,8,'Visits',1,1,'C',true);

$pdf->SetFont('Arial','',11);

$total = 0;

while ($row = $result->fetch_assoc()) {

$url = preg_replace('#https?://#','',$row["url"]);

$pdf->Cell(120,8,$url,1);
$pdf->Cell(40,8,$row["visits"],1,1,'R');

$total += $row["visits"];

}

$pdf->SetFont('Arial','B',11);

$pdf->Cell(120,8,'TOTAL',1);
$pdf->Cell(40,8,$total,1,1,'R');

}

/*
|--------------------------------------------------------------------------
| Analyst Comments
|--------------------------------------------------------------------------
*/

if ($reportId) {

$stmt = $mysqli->prepare("
SELECT comment, created_at
FROM analyst_comments
WHERE report_id = ?
ORDER BY created_at
");

$stmt->bind_param("s",$reportId);
$stmt->execute();

$result = $stmt->get_result();

if ($result->num_rows > 0) {

$pdf->Ln(6);

$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,'Report Comments',0,1);

$pdf->SetDrawColor(180,180,180);
$pdf->Cell(0,0,'',1,1);

$pdf->Ln(4);

while ($row = $result->fetch_assoc()) {

$pdf->SetFont('Arial','I',10);
$dt = new DateTime($row["created_at"], new DateTimeZone("UTC"));
$dt->setTimezone(new DateTimeZone("America/Los_Angeles"));
$pdf->Cell(0,6,'['.$dt->format("M j, Y g:i A T").']',0,1);

$pdf->SetFont('Arial','',11);
$pdf->MultiCell(0,6,$row["comment"]);

$pdf->Ln(3);

}

}

}

/*
|--------------------------------------------------------------------------
| Cleanup temporary chart
|--------------------------------------------------------------------------
*/

if ($tmpChart && file_exists($tmpChart)) {
unlink($tmpChart);
}

/*
|--------------------------------------------------------------------------
| Output PDF
|--------------------------------------------------------------------------
*/

$filename = $report.'-report-'.date("Y-m-d").'.pdf';

$pdf->Output("D",$filename);
exit;