const express = require("express");
const session = require("express-session");

/* ---------- SERVER START TIME (FOR UPTIME) ---------- */
const SERVER_START_TIME = Date.now();

function getUptime() {
    const seconds = Math.floor((Date.now() - SERVER_START_TIME) / 1000);

    const days = Math.floor(seconds / 86400);
    const hours = Math.floor((seconds % 86400) / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;

    return {
        seconds,
        human: `${days}d ${hours}h ${minutes}m ${secs}s`
    };
}

const app = express();
app.use(express.static("/var/www/jaycampbell.dev/hw2/node"));

// Behind Apache reverse proxy
app.set("trust proxy", 1);

app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// ---------------- SESSION (SERVER-SIDE) ----------------
app.use(
    session({
        name: "hw2sid",
        secret: "replace-this-with-a-random-string",
        resave: false,
        saveUninitialized: false,
        cookie: {
            httpOnly: true,
            sameSite: "lax",
            secure: false
        }
    })
);

// ---------------- HELLO HTML ----------------
app.get("/hello-html-node", (req, res) => {
    const ip = req.ip || "unknown";
    const now = new Date().toISOString();
    const uptime = getUptime();

    res.set("Content-Type", "text/html");
    res.send(`<!DOCTYPE html>
<html>
<head>
  <title>Hello, Node! (Express)</title>
</head>
<body>
  <h1>Hello, Node! (Express Server)</h1>
  <p>This page was generated by a standalone Express.js server</p>
  <p>Current time: ${now}</p>
  <p>Your IP address: ${ip}</p>
  <p><small>Server uptime: ${uptime.human}</small></p>
</body>
</html>`);
});

// ---------------- HELLO JSON ----------------
app.get("/hello-json-node", (req, res) => {
    const uptime = getUptime();

    res.json({
        message: "Hello, Node!",
        timestamp: new Date().toISOString(),
        ip: req.ip || "unknown",
        serverUptime: uptime.seconds
    });
});

// ---------------- ENVIRONMENT ----------------
app.get("/environment-node", (req, res) => {
    const uptime = getUptime();

    const requestInfo = {
        Method: req.method,
        URL: req.originalUrl,
        Protocol: req.protocol,
        Host: req.hostname,
        IP: req.headers["x-forwarded-for"]?.split(",")[0] || req.ip,
        "User-Agent": req.headers["user-agent"] || "unknown"
    };

    const envKeys = [
        "HOME",
        "INVOCATION_ID",
        "JOURNAL_STREAM",
        "LANG",
        "LOGNAME",
        "MEMORY_PRESSURE_WATCH",
        "MEMORY_PRESSURE_WRITE",
        "NODE_ENV",
        "PATH",
        "PORT",
        "SYSTEMD_EXEC_PID",
        "USER"
    ];

    res.set("Content-Type", "text/html");
    res.send(`<!DOCTYPE html>
<html>
<head><title>Environment Variables - Express</title></head>
<body>
<h1 align="center">Environment Variables (Express Server)</h1>
<p><small>Server uptime: ${uptime.human}</small></p>
<hr>

<h2>Request Information (from Express)</h2>
${Object.entries(requestInfo)
            .map(([k, v]) => `<b>${k}:</b> ${v}<br />`)
            .join("\n")}

<h2>Process Environment</h2>
${envKeys
            .map(k => `<b>${k}:</b> ${process.env[k] ?? ""}<br />`)
            .join("\n")}

</body>
</html>`);
});

// ---------------- STATE SAVE ----------------
app.post("/state-node", (req, res) => {
    const v = (req.body.value ?? "").trim();
    req.session.savedValue = v.length ? v : null;
    res.redirect("/hw2/node/state-view.html");
});

// ---------------- STATE VIEW / RESET ----------------
app.get("/state-node", (req, res) => {
    const uptime = getUptime();

    if (req.query.reset === "true") {
        req.session.savedValue = null;
        return res.redirect("/hw2/node/state-view.html");
    }

    const value = req.session.savedValue;

    res.set("Content-Type", "text/html");
    res.send(`<!DOCTYPE html>
<html>
<head><title>Node State View</title></head>
<body>
  <h1>Node State – View</h1>
  <p>${value ? `Saved Value: <b>${value}</b>` : "<b>No value saved.</b>"}</p>
  <p><small>Server uptime: ${uptime.human}</small></p>
  <a href="/hw2/node/state-input.html">Edit</a><br>
  <a href="/hw2/node/state-node?reset=true">Clear</a>
</body>
</html>`);
});

// ---------------- ECHO ----------------
app.all("/echo", (req, res) => {
    const uptime = getUptime();

    res.json({
        method: req.method,
        hostname: req.hostname,
        time: new Date().toISOString(),
        ip: req.headers["x-forwarded-for"]?.split(",")[0] || req.ip,
        user_agent: req.headers["user-agent"] || "unknown",
        query: req.query,
        body: req.body,
        serverUptime: uptime.seconds
    });
});

app.listen(3000, () => {
    console.log("Node server running on port 3000");
});
